from pathlib import Path
from typing import Any, Protocol

JsonObject = dict[str, Any]


class Storage(Protocol):
    def write_text(self, path: str | Path, value: str) -> None: ...

    def read_text(self, path: str | Path) -> str: ...

    def write_json(self, path: str | Path, value: JsonObject) -> None: ...

    def read_json(self, path: str | Path) -> JsonObject: ...

    def write_jsonl(self, path: str | Path, records: list[JsonObject]) -> None: ...

    def read_jsonl(self, path: str | Path) -> list[JsonObject]: ...
